CREATE TABLE IF NOT EXISTS user_room (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES user_profile(id),
  room_id INTEGER NOT NULL REFERENCES room(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
