CREATE TABLE IF NOT EXISTS message (
  id SERIAL PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES user_profile(id),
  room_id INTEGER NOT NULL REFERENCES room(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
